export const BRANDS = [
  'BMW', 'Mercedes-Benz', 'Audi', 'Volkswagen', 'Porsche',
  'Hyundai', 'Kia', 'Genesis', 'Lexus', 'Toyota', 'Honda',
  'Chevrolet', 'KG Mobility', 'Renault Korea', 'Volvo',
  'Land Rover', 'Mini', 'Peugeot', 'Subaru', 'Mitsubishi',
  'Nissan', 'Infiniti', 'Maserati', 'Ferrari', 'Lamborghini',
  'Bentley', 'Rolls-Royce', 'Jaguar', 'Ford', 'Jeep', 'Cadillac',
];

export const MODELS_BY_BRAND = {
  'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'M2', 'M3', 'M4', 'M5', 'M8', 'i3', 'i4', 'i7', 'iX'],
  'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'E-Class', 'S-Class', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'SL', 'AMG GT', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'V-Class'],
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'RS3', 'RS4', 'RS6', 'RS7', 'e-tron'],
  'Volkswagen': ['Golf', 'Polo', 'Passat', 'Tiguan', 'Touareg', 'Arteon', 'T-Roc', 'T-Cross', 'Jetta', 'ID.3', 'ID.4', 'ID.5', 'Atlas', 'Sharan', 'Touran', 'Caddy', 'Multivan', 'Scirocco'],
  'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', 'Boxster', 'Cayman', '718', '928'],
  'Hyundai': ['Avante', 'Sonata', 'Grandeur', 'Tucson', 'Santa Fe', 'Palisade', 'Kona', 'Ioniq', 'Ioniq 5', 'Ioniq 6', 'Veloster', 'Staria', 'Casper', 'i30', 'i40', 'Venue', 'Creta', 'Nexo'],
  'Kia': ['Morning', 'Ray', 'Stonic', 'Niro', 'Seltos', 'Sportage', 'Sorento', 'Carnival', 'Stinger', 'Telluride', 'K3', 'K5', 'K7', 'K8', 'K9', 'EV6', 'Soul'],
  'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
  'Lexus': ['IS', 'ES', 'GS', 'LS', 'UX', 'NX', 'RX', 'GX', 'LX', 'RC', 'LC', 'CT'],
  'Toyota': ['Corolla', 'Camry', 'Avalon', 'Yaris', 'Prius', 'RAV4', 'Highlander', 'Land Cruiser', '4Runner', 'Tacoma', 'Tundra', 'Sienna', 'C-HR', 'Supra', '86', 'Venza', 'Crown', 'Sequoia'],
  'Honda': ['Civic', 'Accord', 'CR-V', 'HR-V', 'Pilot', 'Odyssey', 'Fit', 'Insight', 'Ridgeline', 'Passport', 'NSX'],
  'Chevrolet': ['Spark', 'Malibu', 'Cruze', 'Equinox', 'Trailblazer', 'Trax', 'Tahoe', 'Suburban', 'Camaro', 'Corvette', 'Colorado', 'Orlando'],
  'KG Mobility': ['Tivoli', 'Korando', 'Rexton', 'Musso', 'Torres', 'Actyon'],
  'Renault Korea': ['SM3', 'SM5', 'SM6', 'SM7', 'QM3', 'QM6', 'XM3'],
  'Volvo': ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C40'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar', 'Freelander'],
  'Mini': ['Cooper', 'Cooper S', 'Clubman', 'Countryman', 'Convertible', 'Paceman'],
  'Peugeot': ['208', '308', '508', '2008', '3008', '5008', 'RCZ'],
  'Subaru': ['Impreza', 'Legacy', 'Outback', 'Forester', 'XV', 'WRX', 'BRZ', 'Ascent'],
  'Mitsubishi': ['Lancer', 'Outlander', 'Eclipse Cross', 'ASX', 'Pajero', 'Mirage'],
  'Nissan': ['Altima', 'Maxima', 'Sentra', 'Versa', 'Rogue', 'Murano', 'Pathfinder', 'Armada', 'Juke', 'Kicks', 'GT-R', '370Z', 'Leaf', 'Patrol'],
  'Infiniti': ['Q50', 'Q60', 'Q70', 'QX50', 'QX60', 'QX70', 'QX80'],
  'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo', 'MC20'],
  'Ferrari': ['488', 'F8', 'Roma', 'Portofino', 'SF90', '812', 'Purosangue'],
  'Lamborghini': ['Huracan', 'Aventador', 'Urus', 'Revuelto'],
  'Bentley': ['Continental GT', 'Flying Spur', 'Bentayga', 'Mulsanne'],
  'Rolls-Royce': ['Phantom', 'Ghost', 'Wraith', 'Dawn', 'Cullinan', 'Spectre'],
  'Jaguar': ['XE', 'XF', 'XJ', 'F-Type', 'E-Pace', 'F-Pace', 'I-Pace'],
  'Ford': ['Focus', 'Fiesta', 'Fusion', 'Mustang', 'Explorer', 'Escape', 'Edge', 'Expedition', 'Ranger', 'F-150', 'EcoSport', 'Bronco'],
  'Jeep': ['Wrangler', 'Grand Cherokee', 'Cherokee', 'Compass', 'Renegade', 'Gladiator'],
  'Cadillac': ['CT4', 'CT5', 'CT6', 'XT4', 'XT5', 'XT6', 'Escalade'],
};
