// German and English names for Encar's option codes (Encar publishes Korean
// only; see encarOptions.js). Keyed by Encar's optionCd.
export const OPTION_NAMES_DE_EN = {
  '010': ['Schiebedach', 'Sunroof'],
  '001': ['Antiblockiersystem (ABS)', 'Anti-lock brakes (ABS)'],
  '029': ['Xenon-Scheinwerfer (HID)', 'HID headlamps'],
  '075': ['LED-Scheinwerfer', 'LED headlamps'],
  '059': ['Elektrische Heckklappe', 'Power tailgate'],
  '080': ['Soft-Close-Türen', 'Soft-close doors'],
  '024': ['Elektrisch anklappbare Außenspiegel', 'Power-folding side mirrors'],
  '017': ['Leichtmetallfelgen', 'Alloy wheels'],
  '062': ['Dachreling', 'Roof rails'],
  '082': ['Lenkradheizung', 'Heated steering wheel'],
  '083': ['Elektrisch verstellbares Lenkrad', 'Power-adjustable steering wheel'],
  '084': ['Schaltwippen', 'Paddle shifters'],
  '031': ['Multifunktionslenkrad', 'Steering wheel controls'],
  '030': ['Automatisch abblendender Innenspiegel', 'Auto-dimming rear-view mirror'],
  '074': ['Hi-Pass-Mautgerät', 'Hi-Pass toll unit'],
  '006': ['Elektrische Sitze', 'Power seats'],
  '008': ['Memory-Sitze', 'Memory seats'],
  '007': ['Sitzheizung', 'Heated seats'],
  '002': ['Elektronisch geregeltes Fahrwerk (ECS)', 'Electronically controlled suspension (ECS)'],
  '026': ['Fahrerairbag', 'Driver airbag'],
  '027': ['Beifahrerairbag', 'Passenger airbag'],
  '020': ['Seitenairbags', 'Side airbags'],
  '056': ['Kopfairbags', 'Curtain airbags'],
  '019': ['Antriebsschlupfregelung (TCS)', 'Traction control (TCS)'],
  '055': ['Elektronisches Stabilitätsprogramm (ESC)', 'Electronic stability control (ESC)'],
  '033': ['Reifendruckkontrolle (TPMS)', 'Tyre pressure monitoring (TPMS)'],
  '088': ['Spurverlassenswarner (LDWS)', 'Lane departure warning (LDWS)'],
  '003': ['CD-Player', 'CD player'],
  '085': ['Parksensoren vorne', 'Front parking sensors'],
  '032': ['Parksensoren hinten', 'Rear parking sensors'],
  '086': ['Totwinkel-Assistent', 'Blind-spot warning'],
  '058': ['Rückfahrkamera', 'Rear-view camera'],
  '087': ['360-Grad-Kamera', '360° surround-view camera'],
  '004': ['Monitor vorne', 'Front-seat display'],
  '068': ['Tempomat', 'Cruise control'],
  '079': ['Adaptiver Tempomat', 'Adaptive cruise control'],
  '095': ['Head-up-Display (HUD)', 'Head-up display (HUD)'],
  '094': ['Elektrische Parkbremse (EPB)', 'Electronic parking brake (EPB)'],
  '023': ['Klimaautomatik', 'Automatic climate control'],
  '057': ['Smart Key (schlüsselloser Zugang)', 'Smart key (keyless entry)'],
  '015': ['Funk-Zentralverriegelung', 'Remote central locking'],
  '081': ['Regensensor', 'Rain sensor'],
  '097': ['Lichtautomatik', 'Automatic headlights'],
  '005': ['Navigationssystem', 'Navigation system'],
  '092': ['Sonnenschutzrollos hinten seitlich', 'Rear side sunshades'],
  '093': ['Heckscheibenrollo', 'Rear window sunshade'],
  '054': ['Monitore im Fond', 'Rear-seat displays'],
  '096': ['Bluetooth', 'Bluetooth'],
  '072': ['USB-Anschluss', 'USB port'],
  '071': ['AUX-Anschluss', 'AUX input'],
  '014': ['Ledersitze', 'Leather seats'],
  '021': ['Elektrischer Fahrersitz', 'Power driver seat'],
  '035': ['Elektrischer Beifahrersitz', 'Power passenger seat'],
  '089': ['Elektrische Rücksitze', 'Power rear seats'],
  '022': ['Sitzheizung vorne', 'Heated front seats'],
  '063': ['Sitzheizung hinten', 'Heated rear seats'],
  '051': ['Memory-Fahrersitz', 'Memory driver seat'],
  '078': ['Memory-Beifahrersitz', 'Memory passenger seat'],
  '009': ['Sitzbelüftung', 'Ventilated seats'],
  '034': ['Sitzbelüftung Fahrer', 'Ventilated driver seat'],
  '077': ['Sitzbelüftung Beifahrer', 'Ventilated passenger seat'],
  '090': ['Sitzbelüftung hinten', 'Ventilated rear seats'],
  '091': ['Massagesitze', 'Massage seats'],
};
